import React from 'react';
import './plantHistory.css';

export default function PlantHistory({ history, isLoadingHistory, selectedPlantId }) {

    // render loading screen if loading right now
    if (isLoadingHistory) {
        return (
            <div className="phSection">
                <h2>Loading Records...</h2>
                <div className="phLoadingText">Fetching past diagnoses from the database.</div>
            </div>
        );
    }

    // don't need to render any history if there is no plant selected
    if (!selectedPlantId) {
        return (
            <div className="phSection">
                <h2>New Plant Setup</h2>
                <div className="phEmptyText">Upload photos and/or audio to generate the first diagnosis for your plant.</div>
            </div>
        );
    }

    // render the timeline if it exists
    // this part is generated by Gemini
    return (
        <div className="phSection">
            <h2>Medical History</h2>

            <div className="historyTimeline">
                {history.map((record, index) => (
                    <div key={record.id || index} className="phHistoryCard">

                        {/* Diagnosis Number and Timestamp Header */}
                        <h4 className="phCardHeader">
                            Diagnosis #{record.diagnosisNumber} | {new Date(record.timestamp).toLocaleString()}
                        </h4>

                        {/* Render Past Images (if any exist) */}
                        {record.imageURLs && record.imageURLs.length > 0 && (
                            <div className="phMediaGallery">
                                {record.imageURLs.map((url, i) => (
                                    <img
                                        key={i}
                                        src={url}
                                        alt={`Diagnosis photo ${i + 1}`}
                                        className="phPastImage"
                                    />
                                ))}
                            </div>
                        )}

                        {/* Render Past Audio (if it exists) */}
                        {record.audioURL && (
                            <div className="phAudioContainer">
                                <audio controls src={record.audioURL} className="phAudioPlayer">
                                    Your browser does not support the audio element.
                                </audio>
                            </div>
                        )}

                        {/* Render Gemini's Diagnosis Text */}
                        <div className="historyDiagnosisWrapper">
                            <div className="coreDiagnosis">
                                <h2>{record.generatedDiagnosis.condition || 'Unknown Issue'}</h2>
                                <p>
                                    <strong>Summary:</strong> {record.generatedDiagnosis.summary || 'N/A'}
                                </p>
                            </div>

                            <hr className="divider" />

                            <div className="diagnosisDetails">
                                <div className="actionSteps">
                                    <div className="treatmentBlock">
                                        <h3>Treatment Steps</h3>
                                        <ol className="treatmentList">
                                            {(record.generatedDiagnosis.treatmentSteps || []).map((step, i) => (
                                                <li key={i}>{step}</li>
                                            ))}
                                        </ol>
                                    </div>

                                    <div className="preventionBlock">
                                        <h3>Prevention Tips</h3>
                                        <ul className="preventionList">
                                            {(record.generatedDiagnosis.preventionTips || []).map((tip, i) => (
                                                <li key={i}>{tip}</li>
                                            ))}
                                        </ul>
                                    </div>
                                </div>

                                <div className="explanationSection">
                                    <h3>Detailed Explanation</h3>
                                    <p className="explanationText">
                                        {record.generatedDiagnosis.detailedExplanation || 'No detailed explanation provided.'}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}