import React, { useState, useEffect } from 'react';
import PlantHistory from '../components/plantHistory';
import './communityFeed.css'
import ReactGA from "react-ga4";

export default function CommunityFeed() {
    // sets what is on the feed
    const [feed, setFeed] = useState([]);
    // helps render when feed is being loaded
    const [isLoadingFeed, setIsLoadingFeed] = useState(true);

    // state for viewing a specific plant's history
    // contains the history for the diagnosis you selected
    const [selectedHistory, setSelectedHistory] = useState([]);
    // uid of the owner of the plant
    const [selectedPlantOwner, setSelectedPlantOwner] = useState(null);
    // helps render when history is being loaded
    const [isLoadingHistory, setIsLoadingHistory] = useState(false);

    useEffect(() =>  {
        document.title = "Community Feed | PlantCareAI";
    }, []);

    // fetch the top 18 entries on load
    useEffect(() => {
        const fetchFeed = async () => {
            try {
                // call backend for data
                const res = await fetch('/api/plants/community');
                if (!res.ok) {
                    throw new Error(`Failed to fetch community feed: ${res.status}`);
                }
                const data = await res.json();
                setFeed(data.feed || []);
            } catch (err) {
                console.error("Feed error", err);
            } finally {
                setIsLoadingFeed(false);
            }
        };

        ReactGA.event({
            category: "API Request",
            action: "Called Firebase API",
            label: "Get Plant Community Feed"
        })

        fetchFeed();
    }, []);

    // fetch full history when a card is clicked
    const handleViewHistory = async (entry) => {
        setIsLoadingHistory(true);
        setSelectedPlantOwner(entry); // Save the entry so we can show the UID
        ReactGA.event({
            category: "API Request",
            action: "Called Firebase API",
            label: "Get Plant History from Community Feed"
        })

        try {
            // know the userID and plantID from backend query
            const res = await fetch(`/api/plants/${entry.userID}/history?plantID=${entry.plantID}`);
            if (!res.ok) {
                throw new Error(`Failed to fetch history: ${res.status}`);
            }
            const data = await res.json();
            setSelectedHistory(data.history || []);
        } catch (err) {
            console.error("History error", err);
        } finally {
            setIsLoadingHistory(false);
        }
    };

    // If a user has clicked an entry, render the History view
    if (selectedPlantOwner) {
        // Mask the UID for security (shows the first 4 and last 4 characters)
        const maskedUID = `${selectedPlantOwner.userID.slice(0, 4)}...${selectedPlantOwner.userID.slice(-4)}`;

        return (
            <div className="communityFeedContainer">
                {/* back button */}
                <button
                    onClick={() => setSelectedPlantOwner(null)}
                    className="backButton"
                >
                    ← Back to Community Feed
                </button>

                <h2>Plant History: {selectedPlantOwner.name || selectedPlantOwner.plantID}</h2>

                <div className="ownerInfo">
                    <strong>Owner UID:</strong> {maskedUID}
                </div>

                <PlantHistory
                    history={selectedHistory}
                    isLoadingHistory={isLoadingHistory}
                    selectedPlantId={selectedPlantOwner.plantID}
                />
            </div>
        );
    }

    // generated by Gemini
    // main feed
    return (
        <div className="communityFeedContainer">
            <h2>Community Feed: Latest Diagnoses</h2>
            {isLoadingFeed ? (
                <p>Loading community activity...</p>
            ) : (
                <div className="feedGrid">
                    {feed.map((entry, index) => (
                        <div
                            key={index}
                            onClick={() => handleViewHistory(entry)}
                            className="feedCard"
                        >
                            {/* dynamically render the custom name if it exists, fallback to just ID */}
                            <h3>
                                {entry.name
                                    ? `${entry.name} (${entry.plantID})`
                                    : `Plant ID: ${entry.plantID}`}
                            </h3>
                            <p><strong>Condition:</strong> {entry.condition || "View Diagnosis"}</p>
                            <p><strong>Date:</strong> {new Date(entry.timestamp).toLocaleDateString()}</p>

                            <span className="cardActionText">Click to view full history</span>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}