import React, { useState, useEffect } from 'react';
import PlantHistory from '../components/plantHistory';

export default function CommunityFeed() {
    // sets what is on the feed
    const [feed, setFeed] = useState([]);
    // helps render when feed is being loaded
    const [isLoadingFeed, setIsLoadingFeed] = useState(true);

    // state for viewing a specific plant's history
    // contains the history for the diagnosis you selected
    const [selectedHistory, setSelectedHistory] = useState([]);
    // uid of the owner of the plant
    const [selectedPlantOwner, setSelectedPlantOwner] = useState(null);
    // helps render when history is being loaded
    const [isLoadingHistory, setIsLoadingHistory] = useState(false);

    // fetch the top 9 entries on load
    useEffect(() => {
        const fetchFeed = async () => {
            try {
                // call backend for data
                const res = await fetch('/api/plants/community/latest');
                if (!res.ok) {
                    throw new Error(`Failed to fetch community feed: ${res.status}`);
                }
                const data = await res.json();
                setFeed(data.feed || []);
            } catch (err) {
                console.error("Feed error", err);
            } finally {
                setIsLoadingFeed(false);
            }
        };
        fetchFeed();
    }, []);

    // fetch full history when a card is clicked
    const handleViewHistory = async (entry) => {
        setIsLoadingHistory(true);
        setSelectedPlantOwner(entry); // Save the entry so we can show the UID
        try {
            // know the userID and plantID from backend query
            const res = await fetch(`/api/plants/${entry.userID}/history?plantID=${entry.plantID}`);
            if (!res.ok) {
                throw new Error(`Failed to fetch history: ${res.status}`);
            }
            const data = await res.json();
            setSelectedHistory(data.history || []);
        } catch (err) {
            console.error("History error", err);
        } finally {
            setIsLoadingHistory(false);
        }
    };

    // If a user has clicked an entry, render the History view
    if (selectedPlantOwner) {
        // Mask the UID for security (shows the first 4 and last 4 characters)
        const maskedUID = `${selectedPlantOwner.userID.slice(0, 4)}...${selectedPlantOwner.userID.slice(-4)}`;

        return (
            <div className="communityFeedContainer">
                <button
                    onClick={() => setSelectedPlantOwner(null)}
                    style={{ marginBottom: '20px', padding: '8px 16px', cursor: 'pointer' }}
                >
                    ← Back to Community Feed
                </button>

                <h2>Plant History</h2>
                <p><strong>Owner UID:</strong> {maskedUID}</p>

                <PlantHistory
                    history={selectedHistory}
                    isLoadingHistory={isLoadingHistory}
                    selectedPlantId={selectedPlantOwner.plantID}
                />
            </div>
        );
    }

    // generated by Gemini
    return (
        <div className="communityFeedContainer">
            <h2>Community Feed: Latest Diagnoses</h2>
            {isLoadingFeed ? (
                <p>Loading community activity...</p>
            ) : (
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '20px' }}>
                    {feed.map((entry, index) => (
                        <div
                            key={index}
                            onClick={() => handleViewHistory(entry)}
                            style={{ border: '1px solid #ccc', padding: '15px', borderRadius: '8px', cursor: 'pointer', backgroundColor: '#f9f9f9' }}
                        >
                            <h3>Plant ID: {entry.plantID}</h3>
                            <p><strong>Condition:</strong> {entry.condition || "View Diagnosis"}</p>
                            <p><strong>Date:</strong> {new Date(entry.timestamp).toLocaleDateString()}</p>
                            <p style={{ fontSize: '0.85rem', color: '#666' }}>Click to view full history</p>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}