import React, {useEffect, useState} from 'react';
import { auth, provider, signInWithPopup } from "../firebase.js"
import './login.css';
import {GoogleAuthProvider} from "firebase/auth";
import ReactGA from "react-ga4"

export default function Login({ setUser }) {
    // used to change what is rendered while logging in
    const [isLoggingIn, setIsLoggingIn] = useState(false);

    useEffect(() =>  {
        document.title = "Login | PlantCareAI";
    }, []);


    const handleGoogleLogin = async () => {
        setIsLoggingIn(true);

        ReactGA.event({
            category: "API Request",
            action: "Called Firebase Auth API",
            label: "Google Login"
        })

        try {
            // open the Google sign-in pop-up window
            const loginResult = await signInWithPopup(auth, provider);

            // get the Google Photos credential
            const credential = GoogleAuthProvider.credentialFromResult(loginResult);
            const googlePhotosToken = credential.accessToken;

            // get the user from the login result
            const user = loginResult.user;

            console.log("Logged in: ", user.displayName);

            // only give the important stuff from user instead of the whole thing to simplify
            setUser({
                uid: user.uid,
                displayName : user.displayName,
                googlePhotosToken: googlePhotosToken
            });
        } catch (err) {
            console.error("Login failed: ", err);
            alert("Failed to sign in with Google. Please try again.");
        } finally {
            // always want to cancel logging in state when done with this function
            setIsLoggingIn(false);
        }
    }

    // HTML generated by Gemini to make a simple login screen
    return (
        <div className="loginContainer">
            <div className="loginCard">
                <div className="loginHeader">
                    <h1>PlantCareAI</h1>
                    <p>Sign in to diagnose your plants and save your history.</p>
                </div>

                <button
                    className="googleBtn"
                    onClick={handleGoogleLogin}
                    disabled={isLoggingIn}
                >
                    <span className="googleIcon">G</span>
                    {isLoggingIn ? 'Signing in...' : 'Sign in with Google'}
                </button>
            </div>
        </div>
    );

}