import React, { useState } from 'react';
import './login.css';

export default function Login({ setUser }) {
    // used to change what is rendered while logging in
    const [isLoggingIn, setIsLoggingIn] = useState(false);


    const handleGoogleLogin = async () => {
        setIsLoggingIn(true);

        try {
            // add the Google stuff later, just make a skeleton for now
            const mockUser = {
                uid: '12345',
                displayName: 'User'
            };

            console.log("Logged in: " + JSON.stringify(mockUser));
            setUser(mockUser);
        } catch (err) {
            console.error("Login failed: ", err);
            alert("Failed to sign in with Google. Please try again.");
        } finally {
            // always want to cancel logging in state when done with this function
            setIsLoggingIn(false);
        }
    }

    // HTML generated by Gemini to make a simple login screen
    return (
        <div className="loginContainer">
            <div className="loginCard">
                <div className="loginHeader">
                    <h1>PlantCareAI</h1>
                    <p>Sign in to diagnose your plants and save your history.</p>
                </div>

                <button
                    className="googleBtn"
                    onClick={handleGoogleLogin}
                    disabled={isLoggingIn}
                >
                    <span className="googleIcon">G</span>
                    {isLoggingIn ? 'Signing in...' : 'Sign in with Google'}
                </button>
            </div>
        </div>
    );

}